<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_include_net_worth</name>
   <tag></tag>
   <elementGuidId>2ef4fc0e-570d-451d-b829-bd41e67e0551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_include_net_worth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_include_net_worth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fda06f8-3033-47b7-80e0-22bd37fc36f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0cead1b0-dbec-4fb0-878c-e6e872bd8582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>include_net_worth</value>
      <webElementGuid>7b9b2a88-bc73-4cdf-ab14-dc28aeb6cd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_include_net_worth</value>
      <webElementGuid>58390778-2a09-4e52-a8ce-3e68f7a6a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f74dbc32-b9d9-4474-9ff4-eb6a7f3a7739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_include_net_worth&quot;)</value>
      <webElementGuid>bd944a68-43ef-4955-bada-cb8e5bc68801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_include_net_worth']</value>
      <webElementGuid>7c7c0e16-c588-499c-a227-bb707e3e12ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include_net_worth_holder']/div/div/label/input</value>
      <webElementGuid>c37a6426-9d33-4bf1-b4ba-c1e8007ee7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>a9c48c83-6537-44ee-8ff5-a0679661ad21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'include_net_worth' and @id = 'ffInput_include_net_worth']</value>
      <webElementGuid>27a9fee8-a147-4648-947b-9b83cc7d702c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
