<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Default asset accountShared asset ac_afbbdd</name>
   <tag></tag>
   <elementGuidId>93aa8964-beda-49c2-bbb4-f1cb3b7defcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_account_role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_account_role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e4898230-4e38-4ebb-b816-3a8b57cb144f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e697e85-e9f0-48b1-afaa-05e06e81deb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_role</value>
      <webElementGuid>3c0d08ab-2d24-4aaf-8bf2-8c3496a96396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_account_role</value>
      <webElementGuid>0b322b14-5bdb-4c15-a47c-d1d47b9c7790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>013e6e09-c8ec-42c9-b6a2-ec66f071a810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eed0ba1c-b4bc-4793-ac37-175896f80b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default asset accountShared asset accountSavings accountCredit cardCash wallet</value>
      <webElementGuid>469ce95a-a35a-4a8a-b778-985a307a7067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_account_role&quot;)</value>
      <webElementGuid>ed2e2704-a694-4065-a259-e450077e498e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_account_role']</value>
      <webElementGuid>7b5e7142-1ab0-4ff1-bdea-dd8a723c93b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_role_holder']/div/select</value>
      <webElementGuid>d541cbd7-4c7f-4e3b-a6bb-df217120f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>6dc2baa9-9250-41f0-a3f9-47e3ed5f4116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_role' and @id = 'ffInput_account_role' and (text() = 'Default asset accountShared asset accountSavings accountCredit cardCash wallet' or . = 'Default asset accountShared asset accountSavings accountCredit cardCash wallet')]</value>
      <webElementGuid>e21a91a5-0b5e-44cc-8672-785abebbc67b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
