<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Euro ()US Dollar ()</name>
   <tag></tag>
   <elementGuidId>f8207414-0538-42a3-a584-937414c65405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_currency_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_currency_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c66ab904-9f57-4790-92e6-c09dc647b1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>56db2e98-12c5-4de0-9d4b-1cb8a192e272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency_id</value>
      <webElementGuid>6d094094-806a-4995-a89d-23fa47574ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_currency_id</value>
      <webElementGuid>aa1ef6dd-f721-4977-8801-745bc3edc2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e468af9-6bed-4dad-89be-b7e0676063c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>428e5708-cb2b-477d-ad57-e217b7c05c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Euro (€)US Dollar ($)</value>
      <webElementGuid>04461e87-7b47-4e61-9c57-559d6024a5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_currency_id&quot;)</value>
      <webElementGuid>e7717c66-839a-4d9b-b1f5-57a70bc5d626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_currency_id']</value>
      <webElementGuid>654d3428-c447-431d-8338-b40aed5beff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency_id_holder']/div/select</value>
      <webElementGuid>4a873a27-d85c-475d-aa3b-8262af96305a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ac3a2a2e-8568-44ab-935d-a7098cb17335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency_id' and @id = 'ffInput_currency_id' and (text() = 'Euro (€)US Dollar ($)' or . = 'Euro (€)US Dollar ($)')]</value>
      <webElementGuid>5e2f4437-0557-4c2e-8a9e-785eed933097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
