<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_dailyweeklymonthlyquarterlyevery hal_79c7c6</name>
   <tag></tag>
   <elementGuidId>572d689a-ac61-4d33-ab52-86956d49fc40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repeat_freq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repeat_freq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d46f370d-6e10-42f1-aae4-97633beacb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d64f51e-f196-47a8-956c-d7abba85ad0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeat_freq</value>
      <webElementGuid>45e5a9a0-b2e6-44d8-8be4-f499b7710621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repeat_freq</value>
      <webElementGuid>85beb0be-9daa-42d5-ae40-3ef0cbef3652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eaa48cec-c47c-405c-9a33-a5cf29d3e08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12713f48-0f3d-473a-b4f4-e46353a133f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dailyweeklymonthlyquarterlyevery half-yearyearly</value>
      <webElementGuid>e179c688-1a1f-4015-800f-acf04f0ec80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repeat_freq&quot;)</value>
      <webElementGuid>44d7a2d3-6d8b-43c0-b335-4b6240aeb0c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repeat_freq']</value>
      <webElementGuid>04114de1-676e-410d-b738-1bcd87f87ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_freq_holder']/div/select</value>
      <webElementGuid>961b3762-f3b2-4661-871c-acc2bb862cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>eee98e06-abcf-4933-901a-54d686e71c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repeat_freq' and @id = 'ffInput_repeat_freq' and (text() = 'dailyweeklymonthlyquarterlyevery half-yearyearly' or . = 'dailyweeklymonthlyquarterlyevery half-yearyearly')]</value>
      <webElementGuid>7e55c94f-2514-4074-a2f0-a27c1b56c106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
