<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No auto-budgetSet a fixed amount eve_005aeb</name>
   <tag></tag>
   <elementGuidId>cc528a3c-a86c-47dc-af09-2a4d58048702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1169239f-a4d8-4413-89bb-e627f5ad2d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac057421-ee57-4443-9571-06d3f389ff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_type</value>
      <webElementGuid>ab622799-323e-4537-8a70-af2bf62fffb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_type</value>
      <webElementGuid>6d2a25ea-fd95-4538-8b27-43ff6fb9b3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9045456d-5f85-46b3-80fe-44be021c47a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>914576ac-f17e-4ea1-87dc-e5ab27a5d536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending</value>
      <webElementGuid>177dc6aa-0c8e-46c1-9eb4-4f4c5b4065d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_type&quot;)</value>
      <webElementGuid>9fbcc156-f0e6-4277-bbec-ac80b8114ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_type']</value>
      <webElementGuid>1a936bf7-0095-4d2b-aea3-4497bb978494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_type_holder']/div/select</value>
      <webElementGuid>6b7d7829-ed49-4e62-bf91-3c40c7536025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0f313f61-08b9-46bc-ae47-6c4de28030fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_type' and @id = 'ffInput_auto_budget_type' and (text() = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending' or . = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending')]</value>
      <webElementGuid>707d8c12-cfd0-4113-a27b-f44277edef5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
