<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DailyWeeklyMonthlyQuarterlyEvery hal_69941c</name>
   <tag></tag>
   <elementGuidId>f237050d-3640-4468-8e84-18996217b06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>119f828e-1074-47af-86a9-8a32a93ce552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>abdf4255-86f9-4765-9ae4-8d4122ef3966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_period</value>
      <webElementGuid>e9651de3-7ad4-4cf3-8d31-694faf06d612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_period</value>
      <webElementGuid>5aaa90b8-b6ed-47f3-ac7a-79b115a216ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea471ba6-12d0-4448-b19e-f020555f41ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83f2f463-beb2-44d0-853c-0bda8d269a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DailyWeeklyMonthlyQuarterlyEvery half yearYearly</value>
      <webElementGuid>57d524e6-ddad-4b3b-948b-aa88b8707bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_period&quot;)</value>
      <webElementGuid>6f9ff321-c7c0-40a9-923a-59fc15aebcae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_period']</value>
      <webElementGuid>9cc1a562-d3e9-493f-8d25-37dae407dbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_period_holder']/div/select</value>
      <webElementGuid>24dd0392-0bac-4eb5-8193-69fd1dcc9754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>a4703165-d7cb-47b3-b4f2-5d8363619d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_period' and @id = 'ffInput_auto_budget_period' and (text() = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly' or . = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly')]</value>
      <webElementGuid>d30f7402-e720-4a08-b49e-a8db24ebe826</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
