<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_include_net_worth</name>
   <tag></tag>
   <elementGuidId>e2c47da2-cf41-4644-a610-02376140e771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_include_net_worth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_include_net_worth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>faaac89e-8cf2-4889-b521-69ab45a95c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7589bddc-f1ee-49dc-8a81-e565601ba983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>include_net_worth</value>
      <webElementGuid>0acad56a-62a6-43b6-82b7-0b45e59020ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_include_net_worth</value>
      <webElementGuid>dc039bf5-f029-497c-9659-05d05e3b1873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3690398-b638-4e96-9697-d11368d90135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_include_net_worth&quot;)</value>
      <webElementGuid>26518a7b-7927-45ec-8e6e-940567974030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_include_net_worth']</value>
      <webElementGuid>7ff3ef6a-6163-486d-b0ba-46bc9175f597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include_net_worth_holder']/div/div/label/input</value>
      <webElementGuid>2d9f2a11-4b27-4aa5-81ed-87964e462786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>7890d812-0532-452b-86ae-8471de09fa7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'include_net_worth' and @id = 'ffInput_include_net_worth']</value>
      <webElementGuid>1ab14cf2-a5e3-4a8e-aa0d-976079ea0870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
