<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DebtLoanMortgage</name>
   <tag></tag>
   <elementGuidId>054b2bce-1de0-49e7-8e19-07eac15052bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_type_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_type_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d3cf6d7c-13a5-420e-a742-4138232fe8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb7be0c6-3708-4034-9792-f74a945eb0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_type_id</value>
      <webElementGuid>2b6af897-5f96-4681-9a3f-39a8056f8008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_type_id</value>
      <webElementGuid>0695faef-96b9-4b27-9df0-6bc825d0464e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>627c2d48-bb4a-40cf-9b09-f0c37c6a833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>310abd6e-953c-412e-a48c-a3a6a74cce47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DebtLoanMortgage</value>
      <webElementGuid>bf7388de-d1ce-46ac-8134-88743ee8e786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_type_id&quot;)</value>
      <webElementGuid>8cc13db8-feff-414c-b950-382eb66bff35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_type_id']</value>
      <webElementGuid>70437942-c3da-49e2-8c02-8e867cd9a1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_type_id_holder']/div/select</value>
      <webElementGuid>8d7393db-5a27-4b3b-a499-05679fe097a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>87d9b94e-3cd1-40af-859c-f13970edc77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_type_id' and @id = 'ffInput_liability_type_id' and (text() = 'DebtLoanMortgage' or . = 'DebtLoanMortgage')]</value>
      <webElementGuid>ed0d4fe4-3a86-4eaf-8a12-cd0d8f885dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
