<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_I owe this debt to somebody elseI am_93cb18</name>
   <tag></tag>
   <elementGuidId>8b659108-8ec7-46e4-82f1-60bc140cb88d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_direction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_direction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8f1efd91-e38f-4b5e-a0ef-0829c36f4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c771593-eafa-45fd-bc0f-8911225f3565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_direction</value>
      <webElementGuid>acf4c0cd-799c-408d-a586-702fa60e46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_direction</value>
      <webElementGuid>0478e270-9db6-453e-962d-8653bde61061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>949ab134-0583-4249-a888-74624aeb116f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5657fee1-f8de-4582-9607-144df6187702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I owe this debt to somebody elseI am owed this debt</value>
      <webElementGuid>208f6f03-f2a6-4194-980a-26757355b9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_direction&quot;)</value>
      <webElementGuid>54509b82-f4f8-44a3-b59a-d28341b321f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_direction']</value>
      <webElementGuid>95e12f6b-3fbb-4145-8979-ff6e12fe1510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_direction_holder']/div/select</value>
      <webElementGuid>2bcfe988-dca8-456f-b676-220de6871fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>3c5f7460-7a5f-43eb-b877-b21d37773170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_direction' and @id = 'ffInput_liability_direction' and (text() = 'I owe this debt to somebody elseI am owed this debt' or . = 'I owe this debt to somebody elseI am owed this debt')]</value>
      <webElementGuid>0a5478c7-fba4-4bca-ac49-cb2a7cd5a220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
