<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Per dayPer monthPer year</name>
   <tag></tag>
   <elementGuidId>3e13f773-6ac0-47c6-a495-7db0fa5780df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_interest_period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_interest_period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a5f5f08b-47bb-4d70-9670-72392c9c35fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>64922238-96be-4e0e-a810-d04eed7b59f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interest_period</value>
      <webElementGuid>36ea8dc9-8159-4f6d-89af-57a23432baf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_interest_period</value>
      <webElementGuid>c5c2f8b4-3e40-49c6-90a5-d333b9a49242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3706a91f-64c9-4a42-a34a-74c26c75444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>099a205d-a5c1-48ce-b254-13ce13564ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Per dayPer monthPer year</value>
      <webElementGuid>830f67b2-65e6-4f12-a916-10f647fa8bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_interest_period&quot;)</value>
      <webElementGuid>8fd7a096-36fe-441c-b375-99724b56b052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_interest_period']</value>
      <webElementGuid>2c3b7243-9230-4997-a9d8-fac266794e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='interest_period_holder']/div/select</value>
      <webElementGuid>d7050edc-0227-4b31-a67f-18f3306b30aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>d71ddb20-e88c-44e4-a4ee-fd2c8c99ee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'interest_period' and @id = 'ffInput_interest_period' and (text() = 'Per dayPer monthPer year' or . = 'Per dayPer monthPer year')]</value>
      <webElementGuid>fad66b7e-6bb6-4461-a974-3145fa1359c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
