<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sign in to start your session</name>
   <tag></tag>
   <elementGuidId>052bae7d-5b60-4f4a-9e94-e7303d6a4252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.login-box-msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>40c3364e-e06e-4368-a998-2a31824e9dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-box-msg</value>
      <webElementGuid>4f907a52-d819-4b7c-83b5-209ac4c627f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in to start your session</value>
      <webElementGuid>02f78b46-a674-4a11-9774-b34111b7b5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page dark-mode&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body login-card-body&quot;]/p[@class=&quot;login-box-msg&quot;]</value>
      <webElementGuid>b3716646-610e-4169-8966-59e6efc89b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>adcd22d5-8a0a-492d-9e74-f56448664a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sign in to start your session' or . = 'Sign in to start your session')]</value>
      <webElementGuid>fd5fa66e-86df-480e-9e7f-dd62f60ee233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
