<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_actions1value</name>
   <tag></tag>
   <elementGuidId>f9d96a42-0b90-45df-9d0d-68132132ca46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='actions[1][value]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;actions[1][value]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebfd23f1-8bed-4b08-9c2c-a3ad0ebf512a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e3c364b-9559-4d3a-969e-e4869153f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb332b2d-aa47-49e4-a65d-2226f728383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actions[1][value]</value>
      <webElementGuid>7c3b013a-1bd1-4260-8958-89a64630f054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control tt-input</value>
      <webElementGuid>ff394936-53d2-4f8e-9574-e80d443a3c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>tt-3766c7e6-f806-4a37-a7ae-8ed10c7198a7_listbox</value>
      <webElementGuid>5595d743-afde-425f-804b-9c51e4d2811c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>959e7a54-40ba-4602-a8a3-fe8d62c3bd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ad318421-6151-4527-987e-2b6fcb56d947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7201fb39-4bbc-4b40-9add-b0b9ad481b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7760adcd-df9b-412f-92ee-1ced50a7f704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>01cf642b-181c-45c8-b4a2-98dd46a2543c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body rule-action-box&quot;]/table[@class=&quot;table table-condensed table-bordered table-striped&quot;]/tbody[@class=&quot;rule-action-tbody&quot;]/tr[@class=&quot;rule-action-holder&quot;]/td[3]/span[@class=&quot;twitter-typeahead&quot;]/input[@class=&quot;form-control tt-input&quot;]</value>
      <webElementGuid>536dd061-e9ac-4b07-bbb0-8376c2cfcf24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='actions[1][value]']</value>
      <webElementGuid>03449b6e-caef-41c1-9127-bc61bc62349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[4]/div/div/div[2]/table/tbody/tr/td[3]/span/input[2]</value>
      <webElementGuid>ba2c0ce9-e3e1-4d61-b4b9-c67c49cc7781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/input[2]</value>
      <webElementGuid>ab435e8c-7ae1-41ec-b619-9cb579c737e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'actions[1][value]']</value>
      <webElementGuid>60e6b6b5-35c9-4d34-a583-915f5e0ec164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
