<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Default rulesFirst group</name>
   <tag></tag>
   <elementGuidId>f6c7c6f5-3a7e-459a-bcc1-a5866caf8568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_rule_group_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_rule_group_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9249d591-2e60-4de2-a17b-0e59189cba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e9f9d15a-c875-4db2-856e-ded01c97470c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule_group_id</value>
      <webElementGuid>3df33a6e-4a65-456e-a1e1-47763d64945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_rule_group_id</value>
      <webElementGuid>3b9aa555-c41c-4fa3-83a2-e662dd486d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc155628-8d49-4133-8e95-c1be73f911f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28b84c21-7d4c-4a22-92cc-99230a32652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default rulesFirst group</value>
      <webElementGuid>8bfc1887-8408-46f8-ad9b-b3953cc073ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_rule_group_id&quot;)</value>
      <webElementGuid>5f694d52-cf8c-4334-845c-4dc71cd864d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_rule_group_id']</value>
      <webElementGuid>7013837b-2357-4abf-a249-d7eade501d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rule_group_id_holder']/div/select</value>
      <webElementGuid>e00e4a0c-b522-46db-993b-6754edd3c63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>aa3ac229-8fea-4f10-8bad-38db2a30304d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'rule_group_id' and @id = 'ffInput_rule_group_id' and (text() = 'Default rulesFirst group' or . = 'Default rulesFirst group')]</value>
      <webElementGuid>e7b405d0-0232-48fc-bc99-cfbe24260406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
