<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_When a transaction is createdWhen a _cb5a5f</name>
   <tag></tag>
   <elementGuidId>ccb1929e-085b-4202-8355-dfbcf18413e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_trigger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d746b72-1e87-4a4a-b827-840d87bd36f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8d15a2d9-d4d3-48b1-8ace-31908c2b1e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>62d8e4fa-9d94-4822-a169-b3a5798d8553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_trigger</value>
      <webElementGuid>538244cf-c5e5-40cd-8797-5129dbcfbd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>102d3ad1-d661-49af-ab4f-aa8d728b5547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95e193d0-546f-4ac3-a6d2-378af3b9afda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>When a transaction is createdWhen a transaction is updated</value>
      <webElementGuid>49b9e968-247c-4bae-b35c-143b472bc24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_trigger&quot;)</value>
      <webElementGuid>3cbb4726-c093-4871-b207-b53957b4c8cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_trigger']</value>
      <webElementGuid>e4a2a954-ff28-4ffa-b007-b1d65c1cd1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trigger_holder']/div/select</value>
      <webElementGuid>bf13ab05-ddb6-4f81-89c1-d046a8e6c06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5af67768-ca8f-4712-8f9d-449be8740e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'trigger' and @id = 'ffInput_trigger' and (text() = 'When a transaction is createdWhen a transaction is updated' or . = 'When a transaction is createdWhen a transaction is updated')]</value>
      <webElementGuid>b4c6bb8e-ec57-42cc-b74a-e62ba71dc643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
