<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rules</name>
   <tag></tag>
   <elementGuidId>a0cf5460-4bd3-49b4-99cd-6076313b69d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/aside/section/ul/li[8]/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.treeview.menu-open > ul.treeview-menu > li > a > span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d64babc-59d1-4a94-b12c-a682b48b88c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rules</value>
      <webElementGuid>c90f1b52-bb2b-40eb-8ccb-3fea75acc9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;treeview menu-open&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]/span[2]</value>
      <webElementGuid>e78bfc53-63ef-459f-920d-70821ca42485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/aside/section/ul/li[8]/ul/li/a/span[2]</value>
      <webElementGuid>0e215561-f33e-4d60-82a2-822ca2a7cce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a/span[2]</value>
      <webElementGuid>96138cc2-2ec1-4b81-a297-80f9a718653d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rules' or . = 'Rules')]</value>
      <webElementGuid>2f5f5353-d544-4f55-9edc-6fb66815a852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
