<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(none)      Name</name>
   <tag></tag>
   <elementGuidId>2a4441d9-ccef-478c-9eb5-de858c1d1592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bill[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bill[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>29dbd493-8ce9-4944-978f-52f987f03630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bill</value>
      <webElementGuid>5ff5081f-246b-466f-9641-1e64403a772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill[]</value>
      <webElementGuid>382e0c88-06fa-4ae6-9895-32068eb0c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f0a457fe-7169-4aab-a66c-66ba7dd86fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(none)
      Name
      </value>
      <webElementGuid>8f12321e-4c4d-4309-a5a5-81359e4c7c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>fba9c7b5-376d-4915-9e41-b6438c9e0203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bill[]']</value>
      <webElementGuid>5a3415d5-7e2b-4a09-95eb-0d8c8004f68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[5]/div[2]/select</value>
      <webElementGuid>21663b73-9d55-4688-8d10-35bad8f2b422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>169e7ea3-c3c7-47c3-a0ea-c9f2832f6146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Bill' and @name = 'bill[]' and (text() = '(none)
      Name
      ' or . = '(none)
      Name
      ')]</value>
      <webElementGuid>3ef1e15f-a970-4334-bda5-14fa488e429a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
