<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_budget</name>
   <tag></tag>
   <elementGuidId>877932bc-4ffc-4fb5-a4ec-28d54ad5376e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;budget[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='budget[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>150ad413-aa53-4832-81dc-c50f454c6a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Budget</value>
      <webElementGuid>c2226c40-97ad-483e-85a5-d5b037011256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>budget[]</value>
      <webElementGuid>c9b6f76e-cd62-45bf-9991-010eea23ef8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2d0f374a-acf1-45ad-97c2-8505daa43f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(none)
      My Budget
      </value>
      <webElementGuid>b1b2239e-11d2-4d2d-8f77-eb982b39dc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>da363c1f-434c-49aa-aa92-70aff851378a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='budget[]']</value>
      <webElementGuid>1b59d37b-fe83-4a0f-ad5a-ca4b38631ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div/div[2]/select</value>
      <webElementGuid>f25ae649-c4c7-42cf-b0dd-4c8505cfa9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/select</value>
      <webElementGuid>5fcba013-239a-4a8e-a219-419b4c215809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Budget' and @name = 'budget[]' and (text() = '(none)
      My Budget
      ' or . = '(none)
      My Budget
      ')]</value>
      <webElementGuid>0e30b886-954b-469c-85a0-5cbfcd3f424b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
